# Dependencies

paginate:       9
markdown: kramdown
kramdown:  
  parse_block_html: true

collections:
  pages:
    output: true
    permalink: /:collection/:name
  home:
    output: false
    permalink: /:collection/:name
  news:
    output: true
    permalink: /:collection/:name 
  lectures:
    output: true
    permalink: /:collection/:name 
  stories:
    output: true
    permalink: /:collection/:name 
    
paginate_path: /blog/page:num/
